name: CI-Linux

on: [push]

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'
  config: 'Debug'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: install boost, xerces, lcov, gcov
      run: sudo apt install libboost-test-dev libboost-log-dev libxerces-c-dev lcov gcovr
    - name: cmake config
      run: cmake . -B ${{ env.build }}
    - name: make
      run: cmake --build ${{ env.build }}
    - name: run unit tests
      run: cmake --build ${{ env.build }} --target Sugar++Test
    - name: run coverage
      run: cmake --build ${{ env.build }} --target Sugar++_lcov  
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: ${{ env.build }}/Sugar++_lcov.info
        minimum-coverage: 45
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ env.build }}
        update-comment: true
      
      
      
      
      
      
      
      
      
