name: CI-Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Download and install Boost
      uses: MarkusJx/install-boost@v2.4.4
      id: install-boost
      with:
          boost_version: 1.81.0
          toolset: msvc 
          platform_version: 2022
          link: shared
          arch: x86
            # cache: # optional, default is true
            
    - name: install xerces
      run: vcpkg install xerces-c --triplet x64-windows

    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    # Build is not required unless generated source files are used
    - name: Build CMake
      run: cmake --build ${{ env.build }}

    
    #- name: install boost, xerces, lcov, gcov
    #  run: vcpkg install boost-test boost-log xerces-c --triplet x64-windows
    #- name: cmake config
    #  run: |
    #    md build
    #    cd build
    #    cmake ../ -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
    #- name: make
    #  run: cmake --build ./build
    
    - name: run unit tests
      run: cmake --build ./build --target test
      




